/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import Servidor.ServerInterface;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Esteban Gerpe
 */
public class FriendRequests extends javax.swing.JFrame {
    
    private ClientImpl self;
    private ServerInterface server;
    private DefaultListModel requests;

    /**
     * Creates new form FriendRequests
     */
    public FriendRequests(ClientImpl self, ServerInterface server) {
        initComponents();
        this.self = self;
        this.server = server;
        
        this.requests = new DefaultListModel();
        this.jList1.setModel(requests);
        
        for (String request : this.self.getRequests()) {
            this.requests.addElement(request);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Rechazar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.jList1.getSelectedValue() != null) {
            ArrayList<String> toAccept = (ArrayList<String>) this.jList1.getSelectedValuesList();
            for (String newFriend : toAccept) {
                try {
                    this.server.añadirAmigo(this.self, newFriend);
                } catch (RemoteException ex) {
                    Logger.getLogger(FriendRequests.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.self.getRequests().remove(newFriend);
            }
            
            requests = new DefaultListModel();
            this.jList1.setModel(requests);
        
            for (String request : this.self.getRequests()) {
                this.requests.addElement(request);
            }
            this.formWindowClosing(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (this.jList1.getSelectedValue() != null) {
            ArrayList<String> toIgnore = (ArrayList<String>) this.jList1.getSelectedValuesList();
            for (String ignore : toIgnore) {
                try {
                    this.server.eliminarPeticion(this.self, ignore);
                } catch (RemoteException ex) {
                    Logger.getLogger(FriendRequests.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            requests = new DefaultListModel();
            this.jList1.setModel(requests);
        
            for (String request : this.self.getRequests()) {
                this.requests.addElement(request);
            }
            this.formWindowClosing(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (this.self.getRequests().isEmpty()) {
            this.self.getAplication().getjLabel2().setVisible(false);
            this.self.getAplication().getjLabel3().setVisible(false);
        }
        else {
            this.self.getAplication().getjLabel3().setText(Integer.toString(this.self.getRequests().size()));
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
